### ISSUE TITLE
In Lab-15, cheesecave device operator, temperature cannot be set to custom input

### ISSUE THREAD

**Issue by nikunj-phutela** [MicrosoftLearning/AZ-220-Microsoft-Azure-IoT-Developer#54]
In lab-15 whilst taking the cheese cave device, it only works with values passed as integers to the json, but does not take in custom inputs from the command line.

![image](https://user-images.githubusercontent.com/41740876/90141183-6b1c3680-dd98-11ea-8119-b6e445d54c9a.png)
The original code is as shown above

![image](https://user-images.githubusercontent.com/41740876/90141662-0ad9c480-dd99-11ea-8104-eea475b89c40.png)
On changing the values to user input

The error obtained is
![image](https://user-images.githubusercontent.com/41740876/90141798-39579f80-dd99-11ea-92c5-a1e6155b1f00.png)

Can somebody please help with this?

**Comment by darenm** [comment]
Hi - this issue is a little off-topic as your query relates to your code rather than that within the lab. However, I will point you in the right direction:

I see two errors in your code:

1. The temperature and humidity values should be passed as strings (enclosed in single-quotes), rather than javascript numbers.
1. You are not actually inserting the values into the patch string.

If you look at the original JSON, temp and humidity are passed as string values (enclosed by single-quotes):

```csharp
var patch =
        @"{
            tags: {
                customerID: 'Customer1',
                cheeseCave: 'CheeseCave1'
            },
            properties: {
                desired: {
                    patchId: 'set values',
                    temperature: '50',
                    humidity: '85'
                }
            }
        }";
```

In your revised code, you directly embedding your variable names rather than using string interpolation or similar. For example, this means that the JSON parser is trying to assign the literal `temp` as the value of temperature, which fails. What you need to write is something similar to:

String concatenation:

```csharp
var patch =
        @"{
            tags: {
                customerID: 'Customer1',
                cheeseCave: 'CheeseCave1'
            },
            properties: {
                desired: {
                    patchId: 'set values',
                    temperature: '" + temp + @"',
                    humidity: '"+ hum + @"'
                }
            }
        }";
```

String interpolation (note the use of double `{` and `}` )

```csharp
var patch =
      $@"{{
              tags: {{
                   customerID: 'Customer1',
                   cheeseCave: 'CheeseCave1'
               }},
               properties: {{
                   desired: {{
                   patchId: 'set values',
                       temperature: '{temp}',
                       humidity: '{hum}'
                   }}
               }}
         }}";
```

If you need to brush up on your C#, there are some great interactive tutorials here: [https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/](https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/).

**Comment by nikunj-phutela** [comment]
This worked @darenm , thank you for your help!
